/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main.bean.ui.frame;

import com.bsptechs.main.bean.ui.panel.PanelDataTransferGeneral;
import com.bsptechs.main.bean.ui.panel.PanelDataTransferOptions;

/**
 *
 * @author RafaelAhmedov
 */
public class DataTransferFrame extends javax.swing.JFrame {

    /**
     * Creates new form PaneDataTransferFrame
     */
    
    public DataTransferFrame() {
        initComponents();
        PanelDataTransferGeneral general = new PanelDataTransferGeneral();
        PanelDataTransferOptions options = new PanelDataTransferOptions();
        tabbedPane.addTab("General", general);
        tabbedPane.addTab("Options", options);
   
    }

    public static void showDataTransfer() throws Exception {
        DataTransferFrame dt = new DataTransferFrame();//bu duz deyil axi. Current Database anlayishi
        dt.setVisible(true);
    }

    
    public static void main(String[] args) throws Exception {
        DataTransferFrame.showDataTransfer();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked");*/

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Transfer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${background.white}"), this, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 915;
        gridBagConstraints.ipady = 697;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(tabbedPane, gridBagConstraints);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
