/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main.bean.ui.panel;

import com.bsptechs.main.bean.Config;
import com.bsptechs.main.bean.ui.uielement.UiElement;
import com.bsptechs.main.bean.ui.uielement.UiElementConnection;
import com.bsptechs.main.bean.ui.uielement.UiElementDatabase;
import com.bsptechs.main.dao.impl.DatabaseDAOImpl;
import com.bsptechs.main.dao.inter.DatabaseDAOInter;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author RafaelAhmedov
 */
public class PanelDataTransferGeneral extends javax.swing.JPanel {

    private static final DatabaseDAOInter db = new DatabaseDAOImpl();

    /**
     * Creates new form PaneDataTransver
     */
    public PanelDataTransferGeneral() {
	initComponents();

	pnlInformationSourceSide.setVisible(false);
	pnlInformationTargetSide.setVisible(false);

	UiElementDatabase db = null;
	UiElementConnection cn = Config.getCurrentConnection();
	if (cn == null
		&& Config.instance() != null
		&& Config.instance().getConnections() != null
		&& Config.instance().getConnections().size() > 0) {
	    cn = Config.instance().getConnections().get(0);
	}

	db = Config.getCurrentDatabaseName();
	preparePanel(cn, db);
    }

//   public void refreshData() {
//        MainFrameUtility.fillConnectionsIntoJList();
//    }
    public final void preparePanel(UiElementConnection connection, UiElementDatabase database) {
	prepareConnectionCombobox(connection);
	prepareDatabasesCombobox(connection, database);
    }

    

    public void prepareConnectionCombobox(UiElementConnection connection) {

	System.out.println("prepareConnectionCombobox=" + connection);
	comboboxConnectionSource.removeAllItems();
	List<UiElementConnection> list = Config.instance().getConnections();
	if (list == null) {
	    return;
	}

	for (int i = 0; i < list.size(); i++) {
	    comboboxConnectionSource.addItem(list.get(i));
	}
	System.out.println("Config.getCurrentConnection()=" + connection);
	if (connection != null) {
	    comboboxConnectionSource.setSelectedItem(connection);
	}
    }

    public void prepareDatabasesCombobox(UiElementConnection connection, UiElementDatabase database) {
	if (connection == null) {
	    return;
	}
	System.out.println("prepareDatabasesCombobox=" + database);
	comboboxDatabaseSource.removeAllItems();
	List<UiElementDatabase> databases = connection.getDatabases();
	if (databases == null) {
	    databases = db.getAllDatabases(connection);
	}
	for (int i = 0; i < databases.size(); i++) {
	    comboboxDatabaseSource.addItem(databases.get(i));
	}
	comboboxDatabaseSource.setSelectedItem(database);
    }

    public UiElementDatabase getSelectedDatabase() {
	Object obj = comboboxDatabaseSource.getSelectedItem();

	return (UiElementDatabase) obj;
    }

    public UiElementConnection getSelectedConnection() {
	return (UiElementConnection) comboboxConnectionSource.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlfooter = new javax.swing.JPanel();
        jComboBoxSaveProfile = new javax.swing.JComboBox<>();
        btnLoadProfile = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblInformationSource = new javax.swing.JLabel();
        lblInformationTarget = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lable = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProjectName1 = new javax.swing.JLabel();
        lblConnectionType1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlSource = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboboxDatabaseSource = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboboxConnectionSource = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pnlTarget = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlInformationSourceSide = new javax.swing.JPanel();
        lblProjectNameSource = new javax.swing.JLabel();
        lblConnectionTypeSource = new javax.swing.JLabel();
        lblConnectionNameSource = new javax.swing.JLabel();
        lblHostSource = new javax.swing.JLabel();
        lblPortSource = new javax.swing.JLabel();
        lblServerVersionSourse = new javax.swing.JLabel();
        pnlInformationTargetSide = new javax.swing.JPanel();
        lblProjectNameTarget = new javax.swing.JLabel();
        lblConnectionTypeTarget = new javax.swing.JLabel();
        lblConnectionNameTarget = new javax.swing.JLabel();
        lblHostTarget = new javax.swing.JLabel();
        lblPortTarget = new javax.swing.JLabel();
        lblServerVersionTarget = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 650));

        pnlfooter.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxSaveProfile.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxSaveProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Profile", "Save As" }));
        jComboBoxSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSaveProfileActionPerformed(evt);
            }
        });

        btnLoadProfile.setText("Load Profile");
        btnLoadProfile.setBorder(null);
        btnLoadProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoadProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadProfileActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.setBorder(null);

        javax.swing.GroupLayout pnlfooterLayout = new javax.swing.GroupLayout(pnlfooter);
        pnlfooter.setLayout(pnlfooterLayout);
        pnlfooterLayout.setHorizontalGroup(
            pnlfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfooterLayout.createSequentialGroup()
                .addComponent(jComboBoxSaveProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLoadProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlfooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        pnlfooterLayout.setVerticalGroup(
            pnlfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfooterLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSaveProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInformationSource.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInformationSource.setForeground(new java.awt.Color(0, 51, 204));
        lblInformationSource.setText("Information:");

        lblInformationTarget.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInformationTarget.setForeground(new java.awt.Color(0, 51, 204));
        lblInformationTarget.setText("Information:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lable.setText("Project Name:");

        lable2.setText("Connection Type:");

        jLabel3.setText("Connection Name:");

        jLabel4.setText("Host:");

        jLabel5.setText("Port:");

        jLabel6.setText("Server Version:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lable)
            .addComponent(lable2)
            .addComponent(jLabel3)
            .addComponent(jLabel4)
            .addComponent(jLabel5)
            .addComponent(jLabel6)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lable2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblProjectName1.setText("Project Name:");

        lblConnectionType1.setBackground(new java.awt.Color(255, 255, 255));
        lblConnectionType1.setText("Connection Type:");

        jLabel7.setText("Connection Name:");

        jLabel8.setText("Host:");

        jLabel9.setText("Port:");

        jLabel10.setText("Server Version:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProjectName1)
            .addComponent(lblConnectionType1)
            .addComponent(jLabel7)
            .addComponent(jLabel8)
            .addComponent(jLabel9)
            .addComponent(jLabel10)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblProjectName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnectionType1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlSource.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Source:");

        jLabel1.setText("Database:");

        comboboxConnectionSource.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxConnectionSourceItemStateChanged(evt);
            }
        });

        jLabel2.setText("Connection:");

        javax.swing.GroupLayout pnlSourceLayout = new javax.swing.GroupLayout(pnlSource);
        pnlSource.setLayout(pnlSourceLayout);
        pnlSourceLayout.setHorizontalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(comboboxConnectionSource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboboxDatabaseSource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSourceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        pnlSourceLayout.setVerticalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxConnectionSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxDatabaseSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTarget.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Target:");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Database:");

        jRadioButton1.setText("Connection");

        jRadioButton2.setText("File");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTargetLayout = new javax.swing.GroupLayout(pnlTarget);
        pnlTarget.setLayout(pnlTargetLayout);
        pnlTargetLayout.setHorizontalGroup(
            pnlTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTargetLayout.createSequentialGroup()
                .addGroup(pnlTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pnlTargetLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addGap(0, 100, Short.MAX_VALUE))
            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTargetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTargetLayout.setVerticalGroup(
            pnlTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTargetLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("jButton1");

        jLabel15.setText("jLabel15");
        jLabel15.setPreferredSize(new java.awt.Dimension(73, 14));

        jLabel16.setText("jLabel16");

        jLabel17.setText("Target\n\nDatabase\n");

        jLabel19.setText("jLabel19");

        jLabel20.setText("jLabel19");

        pnlInformationSourceSide.setBackground(new java.awt.Color(255, 255, 255));

        lblProjectNameSource.setText("Project Name");

        lblConnectionTypeSource.setText("Connection Type:");

        lblConnectionNameSource.setText("Connection Name:");

        lblHostSource.setText("Host:");

        lblPortSource.setText("Port:");

        lblServerVersionSourse.setText("Server Version:");

        javax.swing.GroupLayout pnlInformationSourceSideLayout = new javax.swing.GroupLayout(pnlInformationSourceSide);
        pnlInformationSourceSide.setLayout(pnlInformationSourceSideLayout);
        pnlInformationSourceSideLayout.setHorizontalGroup(
            pnlInformationSourceSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationSourceSideLayout.createSequentialGroup()
                .addGroup(pnlInformationSourceSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProjectNameSource)
                    .addComponent(lblConnectionTypeSource)
                    .addComponent(lblConnectionNameSource)
                    .addComponent(lblHostSource)
                    .addComponent(lblPortSource)
                    .addComponent(lblServerVersionSourse))
                .addGap(0, 0, 0))
        );
        pnlInformationSourceSideLayout.setVerticalGroup(
            pnlInformationSourceSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationSourceSideLayout.createSequentialGroup()
                .addComponent(lblProjectNameSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnectionTypeSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnectionNameSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHostSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPortSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServerVersionSourse))
        );

        pnlInformationTargetSide.setBackground(new java.awt.Color(255, 255, 255));

        lblProjectNameTarget.setText("Project Name");

        lblConnectionTypeTarget.setText("Connection Type");

        lblConnectionNameTarget.setText("Connection Name");

        lblHostTarget.setText("Host");

        lblPortTarget.setText("Port");

        lblServerVersionTarget.setText("Server Version");

        javax.swing.GroupLayout pnlInformationTargetSideLayout = new javax.swing.GroupLayout(pnlInformationTargetSide);
        pnlInformationTargetSide.setLayout(pnlInformationTargetSideLayout);
        pnlInformationTargetSideLayout.setHorizontalGroup(
            pnlInformationTargetSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationTargetSideLayout.createSequentialGroup()
                .addGroup(pnlInformationTargetSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProjectNameTarget)
                    .addComponent(lblConnectionTypeTarget)
                    .addComponent(lblConnectionNameTarget)
                    .addGroup(pnlInformationTargetSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPortTarget)
                        .addComponent(lblHostTarget))
                    .addComponent(lblServerVersionTarget))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        pnlInformationTargetSideLayout.setVerticalGroup(
            pnlInformationTargetSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationTargetSideLayout.createSequentialGroup()
                .addComponent(lblProjectNameTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnectionTypeTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnectionNameTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHostTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPortTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServerVersionTarget)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel16)
                .addGap(68, 68, 68)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel17))
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInformationSource)
                .addGap(301, 301, 301)
                .addComponent(lblInformationTarget))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlInformationSourceSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlInformationTargetSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlfooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(pnlTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformationSource)
                    .addComponent(lblInformationTarget))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInformationSourceSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInformationTargetSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(pnlfooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSaveProfileActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSaveProfileActionPerformed

    private void btnLoadProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadProfileActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btnLoadProfileActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void comboboxConnectionSourceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxConnectionSourceItemStateChanged
	prepareDatabasesCombobox(getSelectedConnection(), null);
    }//GEN-LAST:event_comboboxConnectionSourceItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadProfile;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<UiElementConnection> comboboxConnectionSource;
    private javax.swing.JComboBox<UiElementDatabase> comboboxDatabaseSource;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<UiElementDatabase> jComboBox3;
    private javax.swing.JComboBox<UiElementConnection> jComboBox4;
    private javax.swing.JComboBox<String> jComboBoxSaveProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lable;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lblConnectionNameSource;
    private javax.swing.JLabel lblConnectionNameTarget;
    private javax.swing.JLabel lblConnectionType1;
    private javax.swing.JLabel lblConnectionTypeSource;
    private javax.swing.JLabel lblConnectionTypeTarget;
    private javax.swing.JLabel lblHostSource;
    private javax.swing.JLabel lblHostTarget;
    private javax.swing.JLabel lblInformationSource;
    private javax.swing.JLabel lblInformationTarget;
    private javax.swing.JLabel lblPortSource;
    private javax.swing.JLabel lblPortTarget;
    private javax.swing.JLabel lblProjectName1;
    private javax.swing.JLabel lblProjectNameSource;
    private javax.swing.JLabel lblProjectNameTarget;
    private javax.swing.JLabel lblServerVersionSourse;
    private javax.swing.JLabel lblServerVersionTarget;
    private javax.swing.JPanel pnlInformationSourceSide;
    private javax.swing.JPanel pnlInformationTargetSide;
    private javax.swing.JPanel pnlSource;
    private javax.swing.JPanel pnlTarget;
    private javax.swing.JPanel pnlfooter;
    // End of variables declaration//GEN-END:variables
}
