package com.bsptechs.main;

import com.bsptechs.main.bean.ui.frame.ConnectionFrame;
import com.bsptechs.main.bean.ui.panel.PanelQuery;
import com.bsptechs.main.bean.Config;
import com.bsptechs.main.bean.ui.tree.CustomJTree;
import com.bsptechs.main.bean.ui.uielement.UiElementConnection;
import com.bsptechs.main.util.Util;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import com.bsptechs.main.bean.ui.frame.DataTransferFrame;
import com.bsptechs.main.util.ImageUtil;

public class Main extends javax.swing.JFrame {

    UiElementConnection conn = null;

   

    public Main() {
        initComponents();
        btnNewQuery.setEnabled(false);
        menuNewQuery.setEnabled(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcons();
        setlablesforInformationPanel(conn);
    }

//    public String getSelectedConnectionName() {
//        DefaultMutableTreeNode root = (DefaultMutableTreeNode) JTree.getModel().getRoot();
//        Enumeration e = root.preorderEnumeration();
//        while (e.hasMoreElements()) {
//            System.out.println(e.nextElement());
//        }
//    }
    public void setlablesforInformationPanel(UiElementConnection element) {
        UiElementConnection conn = element;
        if (conn != null) {
            String name = conn.getName();
            String port = conn.getPort();
            String ipAdress = conn.getIpAdr();
            String userName = conn.getUserName();

            lblconnecteddatabase.setText(name);
            lblisconnectornoconnect.setText("Connected");
            //            lblHost.setText(host);
            lblPort.setText(port);
            lblUserName1.setText(userName);
        } else {
            lblisconnectornoconnect.setText("Not Connection");
        }
//        if (Config.readConfig().getConnections() == null) {
//        } else {
//            lblconnecteddatabase.setText(Config.readConfig().getConnections().get(0).toString());
//
//        }
//
//        if (Config.getCurrentConnection() == null) {
//            lblisconnectornoconnect.setText("Not Connection");
//        }
//        List<UiElementConnection> l = Config.readConfig().getConnections();
//        UiElementConnection cn = l.get(0);
//        lblHost.setText(cn.getName());
//        lblPort.setText(cn.getPort());
//        lblUserName.setText(cn.getUserName());

    }

    public void setIcons() {
        btnNewConnection.setIcon(ImageUtil.getIcon("mainframe/connection.png"));
        btnNewQuery.setIcon(ImageUtil.getIcon("mainframe/newquery.png"));
        btnTable.setIcon(ImageUtil.getIcon("mainframe/table.png"));
        btnView.setIcon(ImageUtil.getIcon("mainframe/view.png"));
        btnFunctions.setIcon(ImageUtil.getIcon("mainframe/function.png"));
        btnEvent.setIcon(ImageUtil.getIcon("mainframe/event.png"));
        btnUsers.setIcon(ImageUtil.getIcon("mainframe/user.png"));
        btnQuery.setIcon(ImageUtil.getIcon("mainframe/query.png"));
        btnReport.setIcon(ImageUtil.getIcon("mainframe/report.png"));
        btnBackup.setIcon(ImageUtil.getIcon("mainframe/backup.png"));
        btnAutomation.setIcon(ImageUtil.getIcon("mainframe/automation.png"));
        btnModel.setIcon(ImageUtil.getIcon("mainframe/model.png"));
        iconinfo.setIcon(ImageUtil.getIconforQueryPanel("/info.png"));
        iconforconnecteddatabase.setIcon(ImageUtil.getIconforMysql("/mysql.png"));
    }

    public void refreshNewQuery() {
        boolean found = false;
        List<UiElementConnection> l = Config.instance().getConnections();
        for (int i = 0; i < l.size(); i++) {
            UiElementConnection cn = l.get(i);
            if (cn.getParentConnection() != null) {
                found = true;
                break;
            }
        }

        btnNewQuery.setEnabled(found);
        menuNewQuery.setEnabled(found);
    }

    private PanelQuery panelQuery = null;

    public void prepare() throws Exception {
        Config.initialize();
        CustomJTree tree = getListTable();
        tree.setRoot(tree.getSelectedRoot());
        List<UiElementConnection> connections = Config.instance().getConnections();
        tree.fillTree(connections);
    }

    public JTabbedPane getTabPaneTable() {
        return tabTables;
    }

    public CustomJTree getListTable() {
        return (CustomJTree) listDatabases;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapper = new javax.swing.JPanel();
        pnlMainTop = new javax.swing.JPanel();
        btnEvent = new javax.swing.JButton();
        btnFunctions = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnModel = new javax.swing.JButton();
        btnAutomation = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnQuery = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnNewConnection = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnNewQuery = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        splitPaneCenter = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDatabases = new com.bsptechs.main.bean.ui.tree.CustomJTree();
        tabbedPaneCenter = new javax.swing.JTabbedPane();
        tabQuery = new javax.swing.JTabbedPane();
        tabDesignTable = new javax.swing.JTabbedPane();
        tabNewTable = new javax.swing.JTabbedPane();
        tabTables = new javax.swing.JTabbedPane();
        pnlInformation = new javax.swing.JPanel();
        iconinfo = new javax.swing.JLabel();
        iconforconnecteddatabase = new javax.swing.JLabel();
        lblconnecteddatabase = new javax.swing.JLabel();
        lblisconnectornoconnect = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblServerVersion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSessions = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSettingLocation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEncoding = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSSHHost = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        menuBarTop = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewConnection = new javax.swing.JMenuItem();
        menuNewQuery = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuDataTransfer = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainTop.setPreferredSize(new java.awt.Dimension(1050, 61));

        btnEvent.setText("Event");
        btnEvent.setBorder(null);
        btnEvent.setContentAreaFilled(false);
        btnEvent.setDefaultCapable(false);
        btnEvent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEvent.setPreferredSize(new java.awt.Dimension(80, 61));
        btnEvent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEventMouseExited(evt);
            }
        });

        btnFunctions.setText("Function");
        btnFunctions.setBorder(null);
        btnFunctions.setContentAreaFilled(false);
        btnFunctions.setDefaultCapable(false);
        btnFunctions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFunctions.setPreferredSize(new java.awt.Dimension(80, 61));
        btnFunctions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFunctions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseExited(evt);
            }
        });

        btnView.setText("View");
        btnView.setBorder(null);
        btnView.setContentAreaFilled(false);
        btnView.setDefaultCapable(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setPreferredSize(new java.awt.Dimension(80, 61));
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnModel.setText("Model");
        btnModel.setBorder(null);
        btnModel.setContentAreaFilled(false);
        btnModel.setDefaultCapable(false);
        btnModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModel.setPreferredSize(new java.awt.Dimension(80, 61));
        btnModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModelMouseExited(evt);
            }
        });
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });

        btnAutomation.setText("Automation");
        btnAutomation.setBorder(null);
        btnAutomation.setContentAreaFilled(false);
        btnAutomation.setDefaultCapable(false);
        btnAutomation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAutomation.setPreferredSize(new java.awt.Dimension(80, 61));
        btnAutomation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAutomation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAutomationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAutomationMouseExited(evt);
            }
        });

        btnBackup.setText("Backup");
        btnBackup.setBorder(null);
        btnBackup.setContentAreaFilled(false);
        btnBackup.setDefaultCapable(false);
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setPreferredSize(new java.awt.Dimension(80, 61));
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.setBorder(null);
        btnReport.setContentAreaFilled(false);
        btnReport.setDefaultCapable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setPreferredSize(new java.awt.Dimension(80, 61));
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnQuery.setText("Query");
        btnQuery.setBorder(null);
        btnQuery.setContentAreaFilled(false);
        btnQuery.setDefaultCapable(false);
        btnQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuery.setPreferredSize(new java.awt.Dimension(80, 61));
        btnQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQueryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQueryMouseExited(evt);
            }
        });

        btnUsers.setText("User");
        btnUsers.setBorder(null);
        btnUsers.setContentAreaFilled(false);
        btnUsers.setDefaultCapable(false);
        btnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsers.setPreferredSize(new java.awt.Dimension(80, 61));
        btnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersMouseExited(evt);
            }
        });
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnNewConnection.setText("New Connection");
        btnNewConnection.setContentAreaFilled(false);
        btnNewConnection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewConnection.setDefaultCapable(false);
        btnNewConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewConnection.setPreferredSize(new java.awt.Dimension(80, 61));
        btnNewConnection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewConnectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewConnectionMouseExited(evt);
            }
        });
        btnNewConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewConnectionActionPerformed(evt);
            }
        });

        btnTable.setText("Table");
        btnTable.setBorder(null);
        btnTable.setContentAreaFilled(false);
        btnTable.setDefaultCapable(false);
        btnTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable.setPreferredSize(new java.awt.Dimension(80, 61));
        btnTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTableMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTableMouseEntered(evt);
            }
        });
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });

        btnNewQuery.setText("New Query");
        btnNewQuery.setBorder(null);
        btnNewQuery.setContentAreaFilled(false);
        btnNewQuery.setDefaultCapable(false);
        btnNewQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewQuery.setName(""); // NOI18N
        btnNewQuery.setPreferredSize(new java.awt.Dimension(80, 61));
        btnNewQuery.setVerifyInputWhenFocusTarget(false);
        btnNewQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewQueryMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewQueryMouseEntered(evt);
            }
        });
        btnNewQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainTopLayout = new javax.swing.GroupLayout(pnlMainTop);
        pnlMainTop.setLayout(pnlMainTopLayout);
        pnlMainTopLayout.setHorizontalGroup(
            pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainTopLayout.createSequentialGroup()
                .addComponent(btnNewConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAutomation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainTopLayout.setVerticalGroup(
            pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutomation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(pnlMainTopLayout.createSequentialGroup()
                .addGroup(pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPaneCenter.setMaximumSize(new java.awt.Dimension(0, 0));

        panelLeft.setBackground(new java.awt.Color(255, 255, 255));
        panelLeft.setMaximumSize(new java.awt.Dimension(10000, 32767));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("connections");
        listDatabases.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        listDatabases.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                listDatabasesTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                listDatabasesTreeExpanded(evt);
            }
        });
        jScrollPane3.setViewportView(listDatabases);

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        splitPaneCenter.setLeftComponent(panelLeft);

        tabbedPaneCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedPaneCenter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbedPaneCenter.setEnabled(false);
        tabbedPaneCenter.setMaximumSize(new java.awt.Dimension(0, 0));

        tabQuery.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("Query", tabQuery);

        tabDesignTable.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("Design Table", tabDesignTable);

        tabNewTable.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("New Table", tabNewTable);
        tabbedPaneCenter.addTab("Tables", tabTables);

        splitPaneCenter.setRightComponent(tabbedPaneCenter);
        tabbedPaneCenter.getAccessibleContext().setAccessibleName("tabbedPaneCenter");

        pnlInformation.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconforconnecteddatabase.setBackground(new java.awt.Color(0, 0, 0));

        lblconnecteddatabase.setText("            ");

        lblisconnectornoconnect.setText("                       ");

        lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl.setText("Server Version:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sessions:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Host:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Port:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("User Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Settings Location:");

        lblSettingLocation.setText("   ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Encoding:");

        lblEncoding.setText("                                  ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("SSH Host:");

        lblSSHHost.setText("                                ");

        lblUserName1.setText("   ");

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(iconinfo))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEncoding))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSSHHost))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(iconforconnecteddatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblisconnectornoconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblconnecteddatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblSettingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl)
                            .addComponent(lblServerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblHost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblPort, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(lblUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 27, Short.MAX_VALUE))
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addComponent(iconinfo)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblconnecteddatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblisconnectornoconnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(iconforconnecteddatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblServerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHost, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEncoding)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSSHHost)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(lblSettingLocation)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addComponent(splitPaneCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))))
        );

        javax.swing.GroupLayout panelWrapperLayout = new javax.swing.GroupLayout(panelWrapper);
        panelWrapper.setLayout(panelWrapperLayout);
        panelWrapperLayout.setHorizontalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainTop, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
            .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelWrapperLayout.setVerticalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWrapperLayout.createSequentialGroup()
                .addComponent(pnlMainTop, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                jMenu1MenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        menuNewConnection.setText("New Connection");
        menuNewConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewConnectionActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewConnection);

        menuNewQuery.setText("New Query");
        menuNewQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewQueryActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewQuery);

        jMenu10.setText("Open Recent");
        jMenu1.add(jMenu10);

        jMenuItem3.setText("Import Connections...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Export Connections...");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("SweetHome Cloud Sign In");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Close Window");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Close Tab");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Exit MySQLIdea");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        menuBarTop.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Copy");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Paste");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Select All");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        menuBarTop.add(jMenu2);

        jMenu3.setText("View");
        menuBarTop.add(jMenu3);

        jMenu4.setText("Favorites");
        menuBarTop.add(jMenu4);

        jMenu5.setText("Tools");

        menuDataTransfer.setText("Data Transfer");
        menuDataTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataTransferActionPerformed(evt);
            }
        });
        jMenu5.add(menuDataTransfer);

        menuBarTop.add(jMenu5);

        jMenu6.setText("Window");
        menuBarTop.add(jMenu6);

        jMenu7.setText("Help");
        menuBarTop.add(jMenu7);

        setJMenuBar(menuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNewQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewQueryActionPerformed
        prepareNewQuery();
    }//GEN-LAST:event_menuNewQueryActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu1MenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_jMenu1MenuDragMouseEntered

    }//GEN-LAST:event_jMenu1MenuDragMouseEntered

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed

    }//GEN-LAST:event_btnTableActionPerformed

    private void btnTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseEntered
        btnTable.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnTableMouseEntered

    private void btnTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseExited
        btnTable.setBorder(null);
    }//GEN-LAST:event_btnTableMouseExited

    private void btnNewConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewConnectionActionPerformed
        ConnectionFrame.showAsRegister();
    }//GEN-LAST:event_btnNewConnectionActionPerformed

    private void btnNewConnectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewConnectionMouseEntered
        btnNewConnection.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnNewConnectionMouseEntered

    private void btnNewConnectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewConnectionMouseExited
        btnNewConnection.setBorder(null);
    }//GEN-LAST:event_btnNewConnectionMouseExited

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseExited
        btnUsers.setBorder(null);
    }//GEN-LAST:event_btnUsersMouseExited

    private void btnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseEntered
        btnUsers.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnUsersMouseEntered

    private void btnQueryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQueryMouseExited
        btnQuery.setBorder(null);
    }//GEN-LAST:event_btnQueryMouseExited

    private void btnQueryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQueryMouseEntered
        btnQuery.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnQueryMouseEntered

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        btnReport.setBorder(null);
    }//GEN-LAST:event_btnReportMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        btnReport.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        btnBackup.setBorder(null);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        btnBackup.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnAutomationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutomationMouseExited
        btnAutomation.setBorder(null);
    }//GEN-LAST:event_btnAutomationMouseExited

    private void btnAutomationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutomationMouseEntered
        btnAutomation.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnAutomationMouseEntered

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnModelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelMouseExited
        btnModel.setBorder(null);
    }//GEN-LAST:event_btnModelMouseExited

    private void btnModelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelMouseEntered
        btnModel.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnModelMouseEntered

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
//        MainFrameUtility.getSelectedConnectionFromList();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        btnView.setBorder(null);
    }//GEN-LAST:event_btnViewMouseExited

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        btnView.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnViewMouseEntered

    private void btnFunctionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseExited
        btnFunctions.setBorder(null);
    }//GEN-LAST:event_btnFunctionsMouseExited

    private void btnFunctionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseEntered
        btnFunctions.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnFunctionsMouseEntered

    private void btnEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventMouseExited
        btnEvent.setBorder(null);
    }//GEN-LAST:event_btnEventMouseExited

    private void btnEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventMouseEntered
        btnEvent.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnEventMouseEntered

    private void btnNewQueryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewQueryMouseEntered
        btnNewQuery.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnNewQueryMouseEntered

    private void btnNewQueryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewQueryMouseExited
        btnNewQuery.setBorder(null);
    }//GEN-LAST:event_btnNewQueryMouseExited

    private void menuNewConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewConnectionActionPerformed
        ConnectionFrame.showAsRegister();
    }//GEN-LAST:event_menuNewConnectionActionPerformed

    private void listDatabasesTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listDatabasesTreeExpanded
    }//GEN-LAST:event_listDatabasesTreeExpanded

    private void listDatabasesTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_listDatabasesTreeCollapsed
    }//GEN-LAST:event_listDatabasesTreeCollapsed

    private void menuDataTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataTransferActionPerformed
        try {
            DataTransferFrame.showDataTransfer();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuDataTransferActionPerformed

    public PanelQuery getPanelQuery() {
        return panelQuery;
    }

    public void prepareNewQuery() {
        try {
            panelQuery = new PanelQuery(Config.getCurrentConnection(), Config.getCurrentDatabaseName());
            tabbedPaneCenter.setEnabled(true);
            Util.addPanelToTab(tabQuery, panelQuery, "Query");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnNewQueryActionPerformed(java.awt.event.ActionEvent evt) {
        prepareNewQuery();
    }

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Config.setMain(new Main());
                    Config.getMain().prepare();
                    Config.getMain().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomation;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnEvent;
    private javax.swing.JButton btnFunctions;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnNewConnection;
    private javax.swing.JButton btnNewQuery;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnUsers;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel iconforconnecteddatabase;
    private javax.swing.JLabel iconinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblEncoding;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblSSHHost;
    private javax.swing.JLabel lblServerVersion;
    private javax.swing.JLabel lblSessions;
    private javax.swing.JLabel lblSettingLocation;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblconnecteddatabase;
    private javax.swing.JLabel lblisconnectornoconnect;
    private javax.swing.JTree listDatabases;
    private javax.swing.JMenuBar menuBarTop;
    private javax.swing.JMenuItem menuDataTransfer;
    private javax.swing.JMenuItem menuNewConnection;
    private javax.swing.JMenuItem menuNewQuery;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelWrapper;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlMainTop;
    private javax.swing.JSplitPane splitPaneCenter;
    private javax.swing.JTabbedPane tabDesignTable;
    private javax.swing.JTabbedPane tabNewTable;
    private javax.swing.JTabbedPane tabQuery;
    private javax.swing.JTabbedPane tabTables;
    private javax.swing.JTabbedPane tabbedPaneCenter;
    // End of variables declaration//GEN-END:variables
}
