/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main;

import com.bsptechs.main.bean.Config;
import com.bsptechs.main.bean.UiElement;
import com.bsptechs.main.util.ui.MainFrameUtility;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTabbedPane;

/**
 *
 * @author RafaelAhmedov
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        btnNewQuery.setEnabled(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void enableNewQuery() {
        btnNewQuery.setEnabled(true);
    }
    private PanelQuery panelQuery = null;

    public void prepare() throws Exception {
        Config.initialize();
       MainFrameUtility.prepareDatabaseList();
        MainFrameUtility.prepareConnectionsList();
        refreshData();

    }
    
    public void refreshData() {
        MainFrameUtility.fillConnectionsIntoJList();
    }

    public JTabbedPane getTabPaneTable() {
        return tabTables;
    }

    public JList getListTable() {
        return listDatabases;
    }

    public JList getListConnections() {
        return listConnections;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapper = new javax.swing.JPanel();
        pnlMainTop = new javax.swing.JPanel();
        btnEvent = new javax.swing.JButton();
        btnFunctions = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnModel = new javax.swing.JButton();
        btnAutomation = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnQuery = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnConnection = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnNewQuery = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        splitPaneCenter = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDatabases = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listConnections = new javax.swing.JList<>();
        tabbedPaneCenter = new javax.swing.JTabbedPane();
        tabQuery = new javax.swing.JTabbedPane();
        tabDesignTable = new javax.swing.JTabbedPane();
        tabNewTable = new javax.swing.JTabbedPane();
        tabTables = new javax.swing.JTabbedPane();
        menuBarTop = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuitemMysqlConnection = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainTop.setPreferredSize(new java.awt.Dimension(1050, 61));

        btnEvent.setText("Event");
        btnEvent.setBorder(null);
        btnEvent.setContentAreaFilled(false);
        btnEvent.setDefaultCapable(false);
        btnEvent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEvent.setPreferredSize(new java.awt.Dimension(80, 61));
        btnEvent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEventMouseExited(evt);
            }
        });

        btnFunctions.setText("Function");
        btnFunctions.setBorder(null);
        btnFunctions.setContentAreaFilled(false);
        btnFunctions.setDefaultCapable(false);
        btnFunctions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFunctions.setPreferredSize(new java.awt.Dimension(80, 61));
        btnFunctions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFunctions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseExited(evt);
            }
        });

        btnView.setText("View");
        btnView.setBorder(null);
        btnView.setContentAreaFilled(false);
        btnView.setDefaultCapable(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setPreferredSize(new java.awt.Dimension(80, 61));
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnModel.setText("Model");
        btnModel.setBorder(null);
        btnModel.setContentAreaFilled(false);
        btnModel.setDefaultCapable(false);
        btnModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModel.setPreferredSize(new java.awt.Dimension(80, 61));
        btnModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModelMouseExited(evt);
            }
        });
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });

        btnAutomation.setText("Automation");
        btnAutomation.setBorder(null);
        btnAutomation.setContentAreaFilled(false);
        btnAutomation.setDefaultCapable(false);
        btnAutomation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAutomation.setPreferredSize(new java.awt.Dimension(80, 61));
        btnAutomation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAutomation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAutomationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAutomationMouseExited(evt);
            }
        });

        btnBackup.setText("Backup");
        btnBackup.setBorder(null);
        btnBackup.setContentAreaFilled(false);
        btnBackup.setDefaultCapable(false);
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setPreferredSize(new java.awt.Dimension(80, 61));
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.setBorder(null);
        btnReport.setContentAreaFilled(false);
        btnReport.setDefaultCapable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setPreferredSize(new java.awt.Dimension(80, 61));
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnQuery.setText("Query");
        btnQuery.setBorder(null);
        btnQuery.setContentAreaFilled(false);
        btnQuery.setDefaultCapable(false);
        btnQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuery.setPreferredSize(new java.awt.Dimension(80, 61));
        btnQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQueryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQueryMouseExited(evt);
            }
        });

        btnUsers.setText("User");
        btnUsers.setBorder(null);
        btnUsers.setContentAreaFilled(false);
        btnUsers.setDefaultCapable(false);
        btnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsers.setPreferredSize(new java.awt.Dimension(80, 61));
        btnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersMouseExited(evt);
            }
        });
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnConnection.setText("Connection");
        btnConnection.setBorder(null);
        btnConnection.setContentAreaFilled(false);
        btnConnection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConnection.setDefaultCapable(false);
        btnConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConnection.setPreferredSize(new java.awt.Dimension(80, 61));
        btnConnection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConnectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConnectionMouseExited(evt);
            }
        });
        btnConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionActionPerformed(evt);
            }
        });

        btnTable.setText("Table");
        btnTable.setBorder(null);
        btnTable.setContentAreaFilled(false);
        btnTable.setDefaultCapable(false);
        btnTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable.setPreferredSize(new java.awt.Dimension(80, 61));
        btnTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTableMouseExited(evt);
            }
        });
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });

        btnNewQuery.setText("New Query");
        btnNewQuery.setBorder(null);
        btnNewQuery.setContentAreaFilled(false);
        btnNewQuery.setDefaultCapable(false);
        btnNewQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewQuery.setName(""); // NOI18N
        btnNewQuery.setPreferredSize(new java.awt.Dimension(80, 61));
        btnNewQuery.setVerifyInputWhenFocusTarget(false);
        btnNewQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewQueryMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewQueryMouseEntered(evt);
            }
        });
        btnNewQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainTopLayout = new javax.swing.GroupLayout(pnlMainTop);
        pnlMainTop.setLayout(pnlMainTopLayout);
        pnlMainTopLayout.setHorizontalGroup(
            pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainTopLayout.createSequentialGroup()
                .addComponent(btnConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAutomation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 237, Short.MAX_VALUE))
        );
        pnlMainTopLayout.setVerticalGroup(
            pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutomation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(pnlMainTopLayout.createSequentialGroup()
                .addGroup(pnlMainTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPaneCenter.setMaximumSize(new java.awt.Dimension(0, 0));

        panelLeft.setBackground(new java.awt.Color(255, 255, 255));
        panelLeft.setMaximumSize(new java.awt.Dimension(10000, 32767));

        listDatabases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDatabasesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listDatabasesMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDatabasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDatabases);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listConnections);

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );

        splitPaneCenter.setLeftComponent(panelLeft);

        tabbedPaneCenter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbedPaneCenter.setEnabled(false);
        tabbedPaneCenter.setMaximumSize(new java.awt.Dimension(0, 0));

        tabQuery.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("Query", tabQuery);

        tabDesignTable.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("Design Table", tabDesignTable);

        tabNewTable.setMaximumSize(new java.awt.Dimension(0, 0));
        tabbedPaneCenter.addTab("New Table", tabNewTable);
        tabbedPaneCenter.addTab("Tables", tabTables);

        splitPaneCenter.setRightComponent(tabbedPaneCenter);
        tabbedPaneCenter.getAccessibleContext().setAccessibleName("tabbedPaneCenter");

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelWrapperLayout = new javax.swing.GroupLayout(panelWrapper);
        panelWrapper.setLayout(panelWrapperLayout);
        panelWrapperLayout.setHorizontalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainTop, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
            .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelWrapperLayout.setVerticalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWrapperLayout.createSequentialGroup()
                .addComponent(pnlMainTop, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                jMenu1MenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        jMenuItem1.setText("New Project");
        jMenu1.add(jMenuItem1);

        jMenu8.setText("New Connection");

        menuitemMysqlConnection.setText("MySQL");
        menuitemMysqlConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemMysqlConnectionActionPerformed(evt);
            }
        });
        jMenu8.add(menuitemMysqlConnection);

        jMenuItem12.setText("PostgreSQL");
        jMenu8.add(jMenuItem12);

        jMenuItem14.setText("Oracle");
        jMenu8.add(jMenuItem14);

        jMenuItem15.setText("SQLite");
        jMenu8.add(jMenuItem15);

        jMenuItem16.setText("SQL Server");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem16);

        jMenu1.add(jMenu8);

        jMenu9.setText("New");
        jMenu1.add(jMenu9);

        jMenuItem2.setText("Open Connection");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu10.setText("Open Recent");
        jMenu1.add(jMenu10);

        jMenuItem3.setText("Import Connections...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Export Connections...");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("SweetHome Cloud Sign In");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Close Window");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Close Tab");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Exit MySQLIdea");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        menuBarTop.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Copy");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Paste");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Select All");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        menuBarTop.add(jMenu2);

        jMenu3.setText("View");
        menuBarTop.add(jMenu3);

        jMenu4.setText("Favorites");
        menuBarTop.add(jMenu4);

        jMenu5.setText("Tools");
        menuBarTop.add(jMenu5);

        jMenu6.setText("Window");
        menuBarTop.add(jMenu6);

        jMenu7.setText("Help");
        menuBarTop.add(jMenu7);

        setJMenuBar(menuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu1MenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_jMenu1MenuDragMouseEntered

    }//GEN-LAST:event_jMenu1MenuDragMouseEntered

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainFrameUtility.fillDatabasesIntoJList();
    }//GEN-LAST:event_btnBackActionPerformed

    private void listDatabasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDatabasesMouseClicked

    }//GEN-LAST:event_listDatabasesMouseClicked

    private void listDatabasesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDatabasesMouseReleased

    }//GEN-LAST:event_listDatabasesMouseReleased

    private void listDatabasesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDatabasesMousePressed

    }//GEN-LAST:event_listDatabasesMousePressed

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTableActionPerformed

    private void btnTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseEntered
        btnTable.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnTableMouseEntered

    private void btnTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseExited
        btnTable.setBorder(null);
    }//GEN-LAST:event_btnTableMouseExited

    private void btnConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionActionPerformed

    }//GEN-LAST:event_btnConnectionActionPerformed

    private void btnConnectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectionMouseEntered
        btnConnection.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnConnectionMouseEntered

    private void btnConnectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectionMouseExited
        btnConnection.setBorder(null);
    }//GEN-LAST:event_btnConnectionMouseExited

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseExited
        btnUsers.setBorder(null);
    }//GEN-LAST:event_btnUsersMouseExited

    private void btnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseEntered
        btnUsers.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnUsersMouseEntered

    private void btnQueryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQueryMouseExited
        btnQuery.setBorder(null);
    }//GEN-LAST:event_btnQueryMouseExited

    private void btnQueryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQueryMouseEntered
        btnQuery.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnQueryMouseEntered

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        btnReport.setBorder(null);
    }//GEN-LAST:event_btnReportMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        btnReport.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        btnBackup.setBorder(null);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        btnBackup.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnAutomationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutomationMouseExited
        btnAutomation.setBorder(null);
    }//GEN-LAST:event_btnAutomationMouseExited

    private void btnAutomationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutomationMouseEntered
        btnAutomation.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnAutomationMouseEntered

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnModelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelMouseExited
        btnModel.setBorder(null);
    }//GEN-LAST:event_btnModelMouseExited

    private void btnModelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelMouseEntered
        btnModel.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnModelMouseEntered

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
//        MainFrameUtility.getSelectedConnectionFromList();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        btnView.setBorder(null);
    }//GEN-LAST:event_btnViewMouseExited

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        btnView.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnViewMouseEntered

    private void btnFunctionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseExited
        btnFunctions.setBorder(null);
    }//GEN-LAST:event_btnFunctionsMouseExited

    private void btnFunctionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseEntered
        btnFunctions.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnFunctionsMouseEntered

    private void btnEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventMouseExited
        btnEvent.setBorder(null);
    }//GEN-LAST:event_btnEventMouseExited

    private void btnEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventMouseEntered
        btnEvent.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnEventMouseEntered

    private void btnNewQueryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewQueryMouseEntered
        btnNewQuery.setBorder(BorderFactory.createBevelBorder(1, Color.lightGray, Color.white));
    }//GEN-LAST:event_btnNewQueryMouseEntered

    private void btnNewQueryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewQueryMouseExited
        btnNewQuery.setBorder(null);
    }//GEN-LAST:event_btnNewQueryMouseExited

    public PanelQuery getPanelQuery() {
        return panelQuery;
    }

    public void prepareNewQuery() {
        try {
            panelQuery = new PanelQuery();
            tabbedPaneCenter.setEnabled(true);
            MainFrameUtility.addPanelToTab(tabQuery, panelQuery, "Query");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnNewQueryActionPerformed(java.awt.event.ActionEvent evt) {
        prepareNewQuery();
    }
    private void menuitemMysqlConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemMysqlConnectionActionPerformed
        MainFrameUtility.showFrameForMySQLConnection(this, tabTables, listConnections, listDatabases);
    }//GEN-LAST:event_menuitemMysqlConnectionActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Config.setMain(new Main());
                    Config.getMain().prepare();
                    Config.getMain().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomation;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnConnection;
    private javax.swing.JButton btnEvent;
    private javax.swing.JButton btnFunctions;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnNewQuery;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnUsers;
    private javax.swing.JButton btnView;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listConnections;
    private javax.swing.JList<String> listDatabases;
    private javax.swing.JMenuBar menuBarTop;
    private javax.swing.JMenuItem menuitemMysqlConnection;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelWrapper;
    private javax.swing.JPanel pnlMainTop;
    private javax.swing.JSplitPane splitPaneCenter;
    private javax.swing.JTabbedPane tabDesignTable;
    private javax.swing.JTabbedPane tabNewTable;
    private javax.swing.JTabbedPane tabQuery;
    private javax.swing.JTabbedPane tabTables;
    private javax.swing.JTabbedPane tabbedPaneCenter;
    // End of variables declaration//GEN-END:variables
}
